name: Cosign installer
on: [push]
jobs:
  test_cosign_action:
    runs-on: ubuntu-latest

    permissions:
      actions: none

    name: Install Cosign and test presence in path
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
      - name: Check install!
        run: cosign version
